version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: # run coverage report
          name: code-coverage
          command: "./node_modules/.bin/nyc report --reporter=text-lcov"
